# Generated by Django 5.2.1 on 2025-05-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_response",
            field=models.TextField(verbose_name="Ответ почтового сервера"),
        ),
    ]
